# Generated by Django 3.0.2 on 2020-06-24 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('bushperc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leafperc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Q', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('stability_class', models.CharField(max_length=200)),
                ('wind', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('RH', models.DecimalField(decimal_places=2, max_digits=5)),
                ('irradiance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.CharField(max_length=200)),
                ('added', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 14, 55, 9, 675843, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
