# Generated by Django 3.0.2 on 2020-06-24 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0002_auto_20200624_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryrequest',
            name='maxdis',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='entryrequest',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 15, 8, 36, 108458, tzinfo=utc)),
        ),
    ]
