# Generated by Django 3.0.8 on 2020-07-14 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0003_auto_20200624_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrequest',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 16, 36, 50, 300299, tzinfo=utc)),
        ),
    ]
