# Generated by Django 3.0.8 on 2020-07-15 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0004_auto_20200714_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrequest',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 6, 59, 9, 220345, tzinfo=utc)),
        ),
    ]
