# Generated by Django 3.0.8 on 2021-02-02 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0005_auto_20200715_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrequest',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 19, 24, 16, 903324, tzinfo=utc)),
        ),
    ]
